/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ceyloncare.home;

import ceyloncare.login.Connect;
import ceyloncare.login.Login;
import ceyloncare.testresult.ManageTestResults;
import ceyloncare.testresult.TestResultRecord;
import ceyloncare.test.ManageTests;
import ceyloncare.user.ManageProfile;
import ceyloncare.user.ChangePassword;
import ceyloncare.doctor.DoctorRecord;
import ceyloncare.patient.PatientRecord;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author Wasura Dananjith
 */
public class LaboratoryHome extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    String username="";
    String type="Laboratory";
    String name="";
    /**
     * Creates new form AdminHome
     * @param getUsername
     */
    public LaboratoryHome(String getUsername) {
        initComponents();
        setLocationRelativeTo(null);
        username=getUsername;
        // Creating the heading based on the username
        this.createHeading(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditProfile = new javax.swing.JButton();
        btnPassword = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtWelcome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuPatient = new javax.swing.JMenu();
        itemSearch = new javax.swing.JMenuItem();
        menuDoctor = new javax.swing.JMenu();
        itemDocSearch = new javax.swing.JMenuItem();
        menuTest = new javax.swing.JMenu();
        itemTestManage = new javax.swing.JMenuItem();
        itemTestResults = new javax.swing.JMenu();
        itemResultsManage = new javax.swing.JMenuItem();
        itemResultsSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Laboratory - Home");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 330, 233, 38));

        btnPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPassword.setText("Change Password");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 383, 233, 38));

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-small.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel-background.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 96, 259, 509));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laboratory-panel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 54, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laboratory-image.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 445));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel-background2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 106, 820, -1));

        txtWelcome.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtWelcome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtWelcome.setText("You are logged in as LABORATORY STAFF . . .");
        getContentPane().add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 38, 591, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeBackground.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        menuMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuPatient.setText("Patient");

        itemSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        itemSearch.setText("Search");
        itemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchActionPerformed(evt);
            }
        });
        menuPatient.add(itemSearch);

        menuMain.add(menuPatient);

        menuDoctor.setText("Doctor");

        itemDocSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        itemDocSearch.setText("Search");
        itemDocSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDocSearchActionPerformed(evt);
            }
        });
        menuDoctor.add(itemDocSearch);

        menuMain.add(menuDoctor);

        menuTest.setText("Test");

        itemTestManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemTestManage.setText("Manage Details");
        itemTestManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTestManageActionPerformed(evt);
            }
        });
        menuTest.add(itemTestManage);

        itemTestResults.setText("Results");

        itemResultsManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        itemResultsManage.setText("Manage Details");
        itemResultsManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemResultsManageActionPerformed(evt);
            }
        });
        itemTestResults.add(itemResultsManage);

        itemResultsSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        itemResultsSearch.setText("Search");
        itemResultsSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemResultsSearchActionPerformed(evt);
            }
        });
        itemTestResults.add(itemResultsSearch);

        menuTest.add(itemTestResults);

        menuMain.add(menuTest);

        setJMenuBar(menuMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDocSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDocSearchActionPerformed
         DoctorRecord frm = new DoctorRecord(type,0);
         frm.setVisible(true);
    }//GEN-LAST:event_itemDocSearchActionPerformed

    private void itemTestManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTestManageActionPerformed
       ManageTests frm = new ManageTests();
       frm.setVisible(true);
    }//GEN-LAST:event_itemTestManageActionPerformed

    private void itemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchActionPerformed
        PatientRecord frm = new PatientRecord(type,0);
        frm.setVisible(true);
    }//GEN-LAST:event_itemSearchActionPerformed

    private void itemResultsManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResultsManageActionPerformed
        ManageTestResults frm = new ManageTestResults(type,1);
        frm.setVisible(true);
    }//GEN-LAST:event_itemResultsManageActionPerformed

    private void itemResultsSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResultsSearchActionPerformed
        TestResultRecord frm = new TestResultRecord(type,0);
        frm.setVisible(true);
    }//GEN-LAST:event_itemResultsSearchActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        ManageProfile frm = new ManageProfile(username);
        frm.setVisible(true);
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        ChangePassword frm = new ChangePassword();
        frm.setVisible(true);
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login login = new Login();
        this.dispose();
        JOptionPane.showMessageDialog(this,"Logout Successful!","Success!",JOptionPane.INFORMATION_MESSAGE);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaboratoryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaboratoryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaboratoryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaboratoryHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaboratoryHome("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPassword;
    private javax.swing.JMenuItem itemDocSearch;
    private javax.swing.JMenuItem itemResultsManage;
    private javax.swing.JMenuItem itemResultsSearch;
    private javax.swing.JMenuItem itemSearch;
    private javax.swing.JMenuItem itemTestManage;
    private javax.swing.JMenu itemTestResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenu menuTest;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables

    private void createHeading(String userName) {
        con=Connect.ConnectDB();
        
        // Selecting name of the user from the user table based on the username and assigned it to the txtWelcome label
        String query = "SELECT * FROM user WHERE username = '" + userName + "'";
        
        try {
            pst=con.prepareStatement(query);
            rs = pst.executeQuery();
            if(rs.next()){
                name=rs.getString("name_user");
                txtWelcome.setText("You are logged in as "+name+" . . . ");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex); 
        }
    }
}
