/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ceyloncare.patient;

import ceyloncare.login.Connect;
import ceyloncare.patient.PatientAdmit;
import ceyloncare.patient.Patient;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wasura Dananjith
 */
public class PatientRecord extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String choice = "";// To identify from which mode the control flow was passed 
    int flag=0;// To identify from which form this form was called
    /**
     * Creates new form PatientRecord
     * @param t
     * @param n
     */
    public PatientRecord(String t,int n) {
        initComponents();
        setLocationRelativeTo(null);
        choice=t;
        flag=n;
        // When this form is called from Admin/Receptionist mode
        if (!((choice.equals("Administrator")) || (choice.equals("Receptionist")))){
            // Set btnAdd invisible
            btnAdd.setVisible(false);
        }
        
        // Get data for jTable1 when this form is loading 
        this.getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Records");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "NIC", "Gender", "Blood Group", "Age", "Guardian", "Phone", "Address", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Search Patient");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnAdd.setText("Add to Form");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.search();
    }//GEN-LAST:event_txtSearchKeyReleased

    // Add data to the Patient/PatientAdmit Form (when btnAdd button is clicked) based on the passed flag value
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            con=Connect.ConnectDB();
            
            // Select the particular row
            int row= jTable1.getSelectedRow();
            String table_click= jTable1.getModel().getValueAt(row, 0).toString();
            
            // Selecting data for a particular patient_id
            String query= "SELECT * FROM patient WHERE patient_id= '" + table_click + "'";
            pst=con.prepareStatement(query);
            rs=  pst.executeQuery();
            
            // Add data to the required fields in the created Form Object
            if(rs.next()){
                // flag=2 means the previous control flow was passed from the Patient Form
                if(flag==2){
                    this.hide();
                    // Create a new object from Patient Form Class
                    Patient frm = new Patient(choice);
                    frm.setVisible(true);
                    
                    String addID=rs.getString("patient_id");
                    frm.txtID.setText(addID);

                    String addName=rs.getString("patient_name");
                    frm.txtName.setText(addName);

                    String addNIC=rs.getString("patient_nic");
                    frm.txtNIC.setText(addNIC);

                    String addGender=rs.getString("patient_gender");
                    frm.cmbGender.setSelectedItem(addGender);
                    
                    String addBG=rs.getString("patient_bg");
                    frm.cmbBloodGroup.setSelectedItem(addBG);
                    
                    String addAge=rs.getString("patient_age");
                    frm.txtAge.setText(addAge);
                    
                    String addGuardian=rs.getString("patient_guardian");
                    frm.txtGuardian.setText(addGuardian);
                    
                    String addPhone=rs.getString("patient_phone");
                    frm.txtContactNo.setText(addPhone);
                    
                    String addAddress=rs.getString("patient_address");
                    frm.txtAddress.setText(addAddress);

                    String addEmail=rs.getString("patient_email");
                    frm.txtEmail.setText(addEmail);

                    frm.btnSave.setEnabled(false);
                    frm.btnDelete.setEnabled(true);
                    frm.btnUpdate.setEnabled(true);
                }
                // flag=1 means the previous control flow was passed from the PatientAdmit Form
                else if (flag==1){
                    this.hide();
                    // Create a new object from PatientAdmit Form Class
                    PatientAdmit frm = new PatientAdmit(choice,null,null,1);
                    frm.setVisible(true);
                    
                    String addID=rs.getString("patient_id");
                    frm.txtPatientID.setText(addID);
                    
                    String addName=rs.getString("patient_name");
                    frm.txtName.setText(addName);
                    
                }
            }

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this,"No row selected!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.hide();
        // flag==2 means this form is called from Patient form, so will be redirected to the same form when window is closing
        if (flag==2){
            Patient frm = new Patient(choice);
            frm.setVisible(true);
        }
        // flag==1 means this form is called from PatientAdmir form, so will be redirected to the same form when window is closing
        else if(flag==1){
            PatientAdmit frm = new PatientAdmit(choice,null,null,1);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRecord("",0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Search patient table
    private void search() {
        try{
            con=Connect.ConnectDB();
            String query="SELECT * FROM patient "
                    + "WHERE patient_id LIKE '%"+txtSearch.getText()+"%' OR patient_name LIKE '%"
                    +txtSearch.getText()+"%' OR patient_nic LIKE '%"+txtSearch.getText()+"%' OR "
                    + "patient_gender LIKE '%"+txtSearch.getText()+"%' OR "
                    +"patient_bg LIKE '%"+ txtSearch.getText()+"%' OR "
                    +"patient_age LIKE '%"+txtSearch.getText()+"%' OR "
                    +"patient_guardian LIKE '%"+txtSearch.getText()+"%' OR "
                    +"patient_phone LIKE '%"+txtSearch.getText()+"%' OR "
                    +"patient_address LIKE '%"+txtSearch.getText()+"%' OR "
                    +"patient_email LIKE '%"+txtSearch.getText()+"%'";
                    
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            DefaultTableModel registrationModel = (DefaultTableModel)jTable1.getModel();
            registrationModel.setRowCount(0);
            while(rs.next())
            {
                registrationModel.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
            }
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }

    // Get data for jTable1 when this form is loading 
    private void getData() {
        con=Connect.ConnectDB();
        try{
            String query="SELECT * FROM patient";
            pst=con.prepareStatement(query);
            rs= pst.executeQuery();
            DefaultTableModel registrationModel = (DefaultTableModel)jTable1.getModel();
            registrationModel.setRowCount(0);
            while(rs.next())
            {
                registrationModel.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
