/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ceyloncare.ward;

import ceyloncare.login.Connect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Wasura Dananjith
 */
public class ManageWard extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int countWard = 0 ; // To generate new ward_no
    /**
     * Creates new form ManageWard
     */
    public ManageWard() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Generates new ward_no for each new ward record
        this.generateID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtWardNo = new javax.swing.JTextField();
        txtCharge = new javax.swing.JTextField();
        txtBeds = new javax.swing.JTextField();
        lbWardType = new javax.swing.JLabel();
        btnWardType = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnGetData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Ward Details");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ward Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ward Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 86, -1, -1));

        jLabel2.setText("Ward Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 35, -1, -1));

        jLabel3.setText("No. of Beds");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 132, -1, -1));

        jLabel4.setText("Charge per Bed");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 178, -1, -1));

        txtWardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWardNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 79, 179, 28));

        txtCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChargeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 171, 179, 28));

        txtBeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBedsActionPerformed(evt);
            }
        });
        jPanel1.add(txtBeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 125, 179, 28));

        lbWardType.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(lbWardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 23, 134, 35));

        btnWardType.setText(">");
        btnWardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWardTypeActionPerformed(evt);
            }
        });
        jPanel1.add(btnWardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 23, -1, 35));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 29, 75, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 63, 75, -1));

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 97, 75, -1));

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 131, 75, -1));

        btnGetData.setText("Get Data");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnGetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 165, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWardNoActionPerformed

    private void txtChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChargeActionPerformed

    private void txtBedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBedsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBedsActionPerformed

    private void btnWardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWardTypeActionPerformed
        this.hide();
        // Load WardTypeSelect form to select a ward type
        WardTypeSelect frm = new WardTypeSelect();
        frm.setVisible(true);
    }//GEN-LAST:event_btnWardTypeActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // Reset all the fields
        this.clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            con=Connect.ConnectDB();
            String wardNo,wardType,beds,charge;
            wardNo=txtWardNo.getText();
            wardType=lbWardType.getText();
            beds=txtBeds.getText();
            charge=txtCharge.getText();

            // Checking whether the necessary fields are empty before inserting data
            if (wardNo.equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Ward Number","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (wardType.equals("")) {
                JOptionPane.showMessageDialog( this, "Please Select Ward Type","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (beds.equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Number of Beds","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
               
            if (charge.equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Charge per Bed","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Query to insert data into ward table
            String query1= "INSERT INTO ward(ward_no,no_of_beds,spec_name,charge_per_bed)"
            + "VALUES('"+ wardNo + "','" + beds + "','" + wardType + "','" + charge + "')";

            pst=con.prepareStatement(query1);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Successfully Inserted","Success",JOptionPane.INFORMATION_MESSAGE);
            btnSave.setEnabled(false);

        } catch (HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // To delete a particular record regarding a ward
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {
            int x = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirm",JOptionPane.YES_NO_OPTION);
            if (x==0)
            {
                con=Connect.ConnectDB();
                String query1= "DELETE FROM ward WHERE ward_no = '" + txtWardNo.getText() + "'";
                pst=con.prepareStatement(query1);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Successfully Deleted","Success",JOptionPane.INFORMATION_MESSAGE);
                this.clear();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // To update a particular record regarding a ward
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            con=Connect.ConnectDB();
            String query1= "UPDATE ward "
            + "SET ward_no='" + txtWardNo.getText() + "',no_of_beds='" + txtBeds.getText()
                    + "',spec_name='" + lbWardType.getText()+ "',charge_per_bed='" + txtCharge.getText()
            + "' WHERE ward_no='" + txtWardNo.getText() + "'";

            pst=con.prepareStatement(query1);
            pst.execute();

            JOptionPane.showMessageDialog(this,"Successfully Updated","Success",JOptionPane.INFORMATION_MESSAGE);
            btnUpdate.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
        this.hide();
        // Load WardRecord form to select already inserted ward details
        WardRecord frm = new WardRecord();
        frm.setVisible(true);
    }//GEN-LAST:event_btnGetDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageWard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnNew;
    public javax.swing.JButton btnSave;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWardType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lbWardType;
    public javax.swing.JTextField txtBeds;
    public javax.swing.JTextField txtCharge;
    public javax.swing.JTextField txtWardNo;
    // End of variables declaration//GEN-END:variables

    // Reset all the fields
    private void clear() {
        this.generateID();
        lbWardType.setText("");
        txtBeds.setText("");
        txtCharge.setText("");
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtWardNo.requestDefaultFocus();
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    // Generates new ward_no for each new ward record
    private void generateID() {
        try{
            con = Connect.ConnectDB();
            String query = "SELECT ward_no FROM ward ORDER BY ward_no";
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            rs.last();
            countWard = Integer.parseInt(rs.getString(1))+1;
            txtWardNo.setText(Integer.toString(countWard));
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }
}
