/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ceyloncare.payment;

import ceyloncare.login.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wasura Dananjith
 */
public class PaymentRecord extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs,rs1,rs2,rs3,rs4 = null;
    PreparedStatement pst = null;
    /**
     * Creates new form PaymentRecord
     */
    public PaymentRecord() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Get data for jTable1 when this form is loading 
        this.getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Record");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Admission Number", "No. of Days", "Payment Date", "Payement Mode", "Total Charge", "Total Paid", "Total Due", "Payment Mode Detals"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Search");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnAdd.setText("Add to Form");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.search();
    }//GEN-LAST:event_txtSearchKeyReleased

    // Add data to the Payment Form when btnAdd button is clicked
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            con=Connect.ConnectDB();
            
            // Select the particular row
            int row= jTable1.getSelectedRow();
            String table_click= jTable1.getModel().getValueAt(row, 1).toString();
            String table_click2 =jTable1.getModel().getValueAt(row, 0).toString();
            
            // Selecting data for a particular admit_id
            String query1= "SELECT a.admit_id,p.patient_id,p.patient_name,a.admit_date,a.disease,a.discharge_date "
            + "FROM admission a,patient p "
            + "WHERE p.patient_id=a.patient_id AND a.admit_id='"+ table_click +"'";

            pst=con.prepareStatement(query1);
            rs1=  pst.executeQuery();

            this.hide();
            // Create a new object from Payment Form Class
            Payment frm = new Payment();
            frm.setVisible(true);
            
            // Add data to the required fields
            if (rs1.next()){
                String addAdmitNo = rs1.getString("admit_id");
                frm.lbAdmitNo.setText(addAdmitNo);

                String addPatientNo = rs1.getString("patient_id");
                frm.lbPatientID.setText(addPatientNo);

                String addName = rs1.getString("patient_name");
                frm.lbName.setText(addName);

                String addAdmitDate = rs1.getString("admit_date");
                frm.lbDate.setText(addAdmitDate);

                String disease = rs1.getString("disease");
                frm.lbDisease.setText(disease);
                
                String date = rs1.getString("discharge_date");
                frm.txtDisDate.setText(date);
            }

            // Selecting data for a particular admit_id
            String query2="SELECT w.ward_no,w.spec_name,w.charge_per_bed FROM ward w,admission a "
            + "WHERE a.ward_no=w.ward_no AND a.admit_id='"+ rs1.getString("admit_id") +"'";

            pst=con.prepareStatement(query2);
            rs2=  pst.executeQuery();

            // Add data to the required fields
            if (rs2.next()){
                String addWardNo = rs2.getString("ward_no");
                frm.lbWardNo.setText(addWardNo);

                String addWardType = rs2.getString("spec_name");
                frm.lbWardType.setText(addWardType);

                String addCharge = rs2.getString("charge_per_bed");
                frm.lbWardCharge.setText(addCharge);
            }

            // Selecting data for a particular admit_id
            String query3 = "SELECT s.doc_id,e.emp_name,d.doc_fee FROM patient_doc_assign s,doctor d,employee e "
            + "WHERE s.admit_id='"+ rs1.getString("admit_id") +"' AND d.emp_id=s.doc_id AND e.emp_id=d.emp_id";

            pst =con.prepareStatement(query3);
            rs3 =pst.executeQuery();

            // Add data to the rows of a table
            DefaultTableModel registrationModel = (DefaultTableModel)frm.jTable2.getModel();
            registrationModel.setRowCount(0);
            float totFee = 0;
            while(rs3.next())
            {
                registrationModel.addRow(new Object[]{rs3.getString(1),rs3.getString(2),rs3.getString(3)});
                totFee+=Float.parseFloat(rs3.getString(3));
            }
            frm.lbTotalFee.setText(Float.toString(totFee));

            // Selecting data for a particular admit_id
            String query4 = "SELECT t.test_id,t.test_name,t.test_fee FROM test t,test_result r "
            + "WHERE r.test_id=t.test_id AND r.admit_id='"+ rs1.getString("admit_id") +"'";

            pst =con.prepareStatement(query4);
            rs4 =pst.executeQuery();

            // Add data to the rows of a table
            DefaultTableModel registrationModel2 = (DefaultTableModel)frm.jTable3.getModel();
            registrationModel2.setRowCount(0);
            float totCharge = 0;
            while(rs4.next())
            {
                registrationModel2.addRow(new Object[]{rs4.getString(1),rs4.getString(2),rs4.getString(3)});
                totCharge+=Float.parseFloat(rs4.getString(3));
            }
            frm.lbTotalTest.setText(Float.toString(totCharge));
            
            // Selecting data for a particular payment_id
            String query5 = "SELECT * from payment WHERE payment_id='"+ table_click2 + "'";
            pst=con.prepareStatement(query5);
            rs = pst.executeQuery();
            
            // Add data to the required fields
            if (rs.next()){
                String addPaymentID = rs.getString("payment_id");
                frm.txtPaymentID.setText(addPaymentID);
                
                String addDays = rs.getString("no_of_days");
                frm.txtDays.setText(addDays);
                
                String addDate = rs.getString("payment_date");
                frm.txtPaymentDate.setText(addDate);
                
                String addPaymentMode = rs.getString("payment_mode");
                frm.cmbPaymentMode.setSelectedItem(addPaymentMode);
                
                String addDetails = rs.getString("payment_mode_details");
                frm.txtPaymentModeDetails.setText(addDetails);
                
                String addTotalWard = Float.toString(Integer.parseInt(addDays)*Float.parseFloat(rs2.getString("charge_per_bed")));
                frm.lbTotalWard.setText(addTotalWard);
                frm.totalWard=Float.parseFloat(addTotalWard);
                
                String addTotalCharge = rs.getString("total_charge");
                frm.lbTotalCharge.setText(addTotalCharge);
                frm.totalCharge=Float.parseFloat(addTotalCharge);
                
                String addTotalPaid = rs.getString("total_paid");
                frm.txtTotalPaid.setText(addTotalPaid);
                frm.totalPaid=Float.parseFloat(addTotalPaid);
                
                String addDue = rs.getString("due_charge");
                frm.lbDue.setText(addDue);
                frm.totalDue=Float.parseFloat(addDue);
                
                frm.btnSave.setEnabled(false);
                frm.btnDelete.setEnabled(true);
                frm.btnUpdate.setEnabled(true);
                            
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this,"No row selected!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.hide();
        Payment frm = new Payment();
        frm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Search payment table
    private void search() {
        try{
            con=Connect.ConnectDB();
            String query="SELECT * FROM payment "
                    + "WHERE (payment_id LIKE '%" + txtSearch.getText() + "%' "
                    + "OR admit_id LIKE '%" + txtSearch.getText() + "%' "
                    + "OR no_of_days LIKE '%" + txtSearch.getText() + "%' "
                    + "OR payment_date LIKE '%" + txtSearch.getText() + "%' "
                    + "OR total_charge LIKE '%" + txtSearch.getText() + "%' "
                    + "OR total_paid LIKE '%" + txtSearch.getText() + "%' "
                    + "OR due_charge LIKE '%" + txtSearch.getText() + "%' "
                    + "OR payment_mode_details LIKE '%" + txtSearch.getText() + "%' "
                    + "OR payment_mode LIKE '%" + txtSearch.getText() + "%') "
                    + "ORDER BY payment_id";
            
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            DefaultTableModel registrationModel = (DefaultTableModel)jTable1.getModel();
            registrationModel.setRowCount(0);
            while(rs.next())
            {
                registrationModel.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }

    // Get data for jTable1 when this form is loading 
    private void getData() {
        con=Connect.ConnectDB();
        try{
            String query="SELECT * FROM payment";
            
            pst=con.prepareStatement(query);
            rs= pst.executeQuery();
            DefaultTableModel registrationModel = (DefaultTableModel)jTable1.getModel();
            registrationModel.setRowCount(0);
            while(rs.next())
            {
                registrationModel.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
